name: AS03 - Test MusicFinder API

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build and run the application
      run: |
        ./mvnw clean package
        java -jar target/*.jar &

    - name: Wait for application to start
      run: sleep 10

    - name: Run API tests
      run: |
        set -e

        echo "Testing /findMusic - Happy Path"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic?artist=Coldplay&song=Yellow" | grep 200

        echo "Testing /findMusic - Missing Parameters (Expect 400)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic" | grep 400 || echo "Failed: Missing parameters test"

        echo "Testing /findMusic/factory - Happy Path (YouTube)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/factory?artist=Coldplay&song=Yellow&provider=youtube" | grep 200

        echo "Testing /findMusic/factory - Happy Path (Lyrics)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/factory?artist=Coldplay&song=Yellow&provider=lyrics" | grep 200

        echo "Testing /findMusic/factory - Invalid Provider (Expect 400)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/factory?artist=Coldplay&song=Yellow&provider=invalidProvider" | grep 400 || echo "Failed: Invalid provider test"

        echo "Testing /findMusic/decorator - Happy Path (YouTube)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/decorator?artist=Coldplay&song=Yellow&provider=youtube" | grep 200

        echo "Testing /findMusic/decorator - Happy Path (Lyrics)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/decorator?artist=Coldplay&song=Yellow&provider=lyrics" | grep 200

        echo "Testing /findMusic/strategy - Happy Path (Exact)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/strategy?artist=Coldplay&song=Yellow&strategy=exact" | grep 200

        echo "Testing /findMusic/strategy - Happy Path (Fuzzy)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/strategy?artist=Coldplay&song=Yellow&strategy=fuzzy" | grep 200

        echo "Testing /findMusic/strategy - Invalid Strategy (Expect 400)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/strategy?artist=Coldplay&song=Yellow&strategy=invalidStrategy" | grep 400 || echo "Failed: Invalid strategy test"

        echo "Testing Invalid Endpoint (Expect 404)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/nonexistentEndpoint" | grep 404 || echo "Failed: Invalid endpoint test"

        echo "Testing /findMusic/strategy - First Request (Cache Miss)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/strategy?artist=Coldplay&song=Yellow&strategy=exact" | grep 200

        echo "Testing /findMusic/strategy - Second Request (Cache Hit)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/strategy?artist=Coldplay&song=Yellow&strategy=exact" | grep 200

        echo "Testing /findMusic/strategy - Different Strategy (Cache Miss)"
        curl -s -o /dev/null -w "%{http_code}" "http://localhost:8080/findMusic/strategy?artist=Coldplay&song=Yellow&strategy=fuzzy" | grep 200

